### ISSUE TITLE
Permission to use StockScraper

### ISSUE THREAD

**Issue by josuebrunel** [gurch101/StockScraper#7]
Hi @gurch101, 
I'm writing a python wrapper of the *Yahoo! Query Language* called **[mYQL](https://github.com/josuebrunel/myql)** and i would like to know if i can add ***StockScraper*** to that library with mention that all rights are reserved to you.

Thanks

**Comment by gurch101** [comment]
hi Josue,

sure!

thanks,
Gurch

**Comment by josuebrunel** [comment]
Thank you @gurch101 :wink:
